{% set name = "empix" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/empix-{{ version }}.tar.gz
  sha256: f653534a2988b38a1ef583f7d5b8b6bcc086bdfbe27392ba4431c336eed29da8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - czekitout
    - fancytypes >=1.0.0
    - hyperspy
    - pyfai
    - numba

test:
  imports:
    - empix
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/empix/
  summary: Contains tools for analyzing electron microscopy data that are not available in ``hyperspy``.
  dev_url: https://github.com/mrfitzpa/empix
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrfitzpa
